# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.account_property_dto import AccountPropertyDTO  # noqa: F401,E501


class AccountPropertiesDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'properties': 'list[AccountPropertyDTO]'
    }

    attribute_map = {
        'address': 'address',
        'properties': 'properties'
    }

    def __init__(self, address=None, properties=None):  # noqa: E501
        """AccountPropertiesDTO - a model defined in Swagger"""  # noqa: E501

        self._address = None
        self._properties = None
        self.discriminator = None

        self.address = address
        self.properties = properties

    @property
    def address(self):
        """Gets the address of this AccountPropertiesDTO.  # noqa: E501


        :return: The address of this AccountPropertiesDTO.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this AccountPropertiesDTO.


        :param address: The address of this AccountPropertiesDTO.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def properties(self):
        """Gets the properties of this AccountPropertiesDTO.  # noqa: E501


        :return: The properties of this AccountPropertiesDTO.  # noqa: E501
        :rtype: list[AccountPropertyDTO]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this AccountPropertiesDTO.


        :param properties: The properties of this AccountPropertiesDTO.  # noqa: E501
        :type: list[AccountPropertyDTO]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountPropertiesDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountPropertiesDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
