# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.account_dto import AccountDTO  # noqa: F401,E501
from swagger_client.models.account_meta_dto import AccountMetaDTO  # noqa: F401,E501


class AccountInfoDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meta': 'AccountMetaDTO',
        'account': 'AccountDTO'
    }

    attribute_map = {
        'meta': 'meta',
        'account': 'account'
    }

    def __init__(self, meta=None, account=None):  # noqa: E501
        """AccountInfoDTO - a model defined in Swagger"""  # noqa: E501

        self._meta = None
        self._account = None
        self.discriminator = None

        self.meta = meta
        self.account = account

    @property
    def meta(self):
        """Gets the meta of this AccountInfoDTO.  # noqa: E501


        :return: The meta of this AccountInfoDTO.  # noqa: E501
        :rtype: AccountMetaDTO
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this AccountInfoDTO.


        :param meta: The meta of this AccountInfoDTO.  # noqa: E501
        :type: AccountMetaDTO
        """
        if meta is None:
            raise ValueError("Invalid value for `meta`, must not be `None`")  # noqa: E501

        self._meta = meta

    @property
    def account(self):
        """Gets the account of this AccountInfoDTO.  # noqa: E501


        :return: The account of this AccountInfoDTO.  # noqa: E501
        :rtype: AccountDTO
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this AccountInfoDTO.


        :param account: The account of this AccountInfoDTO.  # noqa: E501
        :type: AccountDTO
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountInfoDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountInfoDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
