# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.u_int64_dto import UInt64DTO  # noqa: F401,E501


class AliasDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'int',
        'mosaic_id': 'UInt64DTO',
        'address': 'str'
    }

    attribute_map = {
        'type': 'type',
        'mosaic_id': 'mosaicId',
        'address': 'address'
    }

    def __init__(self, type=None, mosaic_id=None, address=None):  # noqa: E501
        """AliasDTO - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._mosaic_id = None
        self._address = None
        self.discriminator = None

        self.type = type
        if mosaic_id is not None:
            self.mosaic_id = mosaic_id
        if address is not None:
            self.address = address

    @property
    def type(self):
        """Gets the type of this AliasDTO.  # noqa: E501


        :return: The type of this AliasDTO.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AliasDTO.


        :param type: The type of this AliasDTO.  # noqa: E501
        :type: int
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def mosaic_id(self):
        """Gets the mosaic_id of this AliasDTO.  # noqa: E501


        :return: The mosaic_id of this AliasDTO.  # noqa: E501
        :rtype: UInt64DTO
        """
        return self._mosaic_id

    @mosaic_id.setter
    def mosaic_id(self, mosaic_id):
        """Sets the mosaic_id of this AliasDTO.


        :param mosaic_id: The mosaic_id of this AliasDTO.  # noqa: E501
        :type: UInt64DTO
        """

        self._mosaic_id = mosaic_id

    @property
    def address(self):
        """Gets the address of this AliasDTO.  # noqa: E501


        :return: The address of this AliasDTO.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this AliasDTO.


        :param address: The address of this AliasDTO.  # noqa: E501
        :type: str
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AliasDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AliasDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
