# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.u_int64_dto import UInt64DTO  # noqa: F401,E501


class BlockchainScoreDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'score_high': 'UInt64DTO',
        'score_low': 'UInt64DTO'
    }

    attribute_map = {
        'score_high': 'scoreHigh',
        'score_low': 'scoreLow'
    }

    def __init__(self, score_high=None, score_low=None):  # noqa: E501
        """BlockchainScoreDTO - a model defined in Swagger"""  # noqa: E501

        self._score_high = None
        self._score_low = None
        self.discriminator = None

        self.score_high = score_high
        self.score_low = score_low

    @property
    def score_high(self):
        """Gets the score_high of this BlockchainScoreDTO.  # noqa: E501


        :return: The score_high of this BlockchainScoreDTO.  # noqa: E501
        :rtype: UInt64DTO
        """
        return self._score_high

    @score_high.setter
    def score_high(self, score_high):
        """Sets the score_high of this BlockchainScoreDTO.


        :param score_high: The score_high of this BlockchainScoreDTO.  # noqa: E501
        :type: UInt64DTO
        """
        if score_high is None:
            raise ValueError("Invalid value for `score_high`, must not be `None`")  # noqa: E501

        self._score_high = score_high

    @property
    def score_low(self):
        """Gets the score_low of this BlockchainScoreDTO.  # noqa: E501


        :return: The score_low of this BlockchainScoreDTO.  # noqa: E501
        :rtype: UInt64DTO
        """
        return self._score_low

    @score_low.setter
    def score_low(self, score_low):
        """Sets the score_low of this BlockchainScoreDTO.


        :param score_low: The score_low of this BlockchainScoreDTO.  # noqa: E501
        :type: UInt64DTO
        """
        if score_low is None:
            raise ValueError("Invalid value for `score_low`, must not be `None`")  # noqa: E501

        self._score_low = score_low

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BlockchainScoreDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockchainScoreDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
