# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.merkle_proof_info_payload import MerkleProofInfoPayload  # noqa: F401,E501


class MerkleProofInfoDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payload': 'MerkleProofInfoPayload',
        'type': 'str'
    }

    attribute_map = {
        'payload': 'payload',
        'type': 'type'
    }

    def __init__(self, payload=None, type=None):  # noqa: E501
        """MerkleProofInfoDTO - a model defined in Swagger"""  # noqa: E501

        self._payload = None
        self._type = None
        self.discriminator = None

        self.payload = payload
        self.type = type

    @property
    def payload(self):
        """Gets the payload of this MerkleProofInfoDTO.  # noqa: E501


        :return: The payload of this MerkleProofInfoDTO.  # noqa: E501
        :rtype: MerkleProofInfoPayload
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this MerkleProofInfoDTO.


        :param payload: The payload of this MerkleProofInfoDTO.  # noqa: E501
        :type: MerkleProofInfoPayload
        """
        if payload is None:
            raise ValueError("Invalid value for `payload`, must not be `None`")  # noqa: E501

        self._payload = payload

    @property
    def type(self):
        """Gets the type of this MerkleProofInfoDTO.  # noqa: E501


        :return: The type of this MerkleProofInfoDTO.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MerkleProofInfoDTO.


        :param type: The type of this MerkleProofInfoDTO.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MerkleProofInfoDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerkleProofInfoDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
