# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.mosaic_definition_dto import MosaicDefinitionDTO  # noqa: F401,E501
from swagger_client.models.mosaic_meta_dto import MosaicMetaDTO  # noqa: F401,E501


class MosaicInfoDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meta': 'MosaicMetaDTO',
        'mosaic': 'MosaicDefinitionDTO'
    }

    attribute_map = {
        'meta': 'meta',
        'mosaic': 'mosaic'
    }

    def __init__(self, meta=None, mosaic=None):  # noqa: E501
        """MosaicInfoDTO - a model defined in Swagger"""  # noqa: E501

        self._meta = None
        self._mosaic = None
        self.discriminator = None

        self.meta = meta
        self.mosaic = mosaic

    @property
    def meta(self):
        """Gets the meta of this MosaicInfoDTO.  # noqa: E501


        :return: The meta of this MosaicInfoDTO.  # noqa: E501
        :rtype: MosaicMetaDTO
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this MosaicInfoDTO.


        :param meta: The meta of this MosaicInfoDTO.  # noqa: E501
        :type: MosaicMetaDTO
        """
        if meta is None:
            raise ValueError("Invalid value for `meta`, must not be `None`")  # noqa: E501

        self._meta = meta

    @property
    def mosaic(self):
        """Gets the mosaic of this MosaicInfoDTO.  # noqa: E501


        :return: The mosaic of this MosaicInfoDTO.  # noqa: E501
        :rtype: MosaicDefinitionDTO
        """
        return self._mosaic

    @mosaic.setter
    def mosaic(self, mosaic):
        """Sets the mosaic of this MosaicInfoDTO.


        :param mosaic: The mosaic of this MosaicInfoDTO.  # noqa: E501
        :type: MosaicDefinitionDTO
        """
        if mosaic is None:
            raise ValueError("Invalid value for `mosaic`, must not be `None`")  # noqa: E501

        self._mosaic = mosaic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MosaicInfoDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MosaicInfoDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
