# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.multisig_account_info_dto import MultisigAccountInfoDTO  # noqa: F401,E501


class MultisigAccountGraphInfoDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'level': 'int',
        'multisig_entries': 'list[MultisigAccountInfoDTO]'
    }

    attribute_map = {
        'level': 'level',
        'multisig_entries': 'multisigEntries'
    }

    def __init__(self, level=None, multisig_entries=None):  # noqa: E501
        """MultisigAccountGraphInfoDTO - a model defined in Swagger"""  # noqa: E501

        self._level = None
        self._multisig_entries = None
        self.discriminator = None

        self.level = level
        self.multisig_entries = multisig_entries

    @property
    def level(self):
        """Gets the level of this MultisigAccountGraphInfoDTO.  # noqa: E501


        :return: The level of this MultisigAccountGraphInfoDTO.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this MultisigAccountGraphInfoDTO.


        :param level: The level of this MultisigAccountGraphInfoDTO.  # noqa: E501
        :type: int
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")  # noqa: E501

        self._level = level

    @property
    def multisig_entries(self):
        """Gets the multisig_entries of this MultisigAccountGraphInfoDTO.  # noqa: E501


        :return: The multisig_entries of this MultisigAccountGraphInfoDTO.  # noqa: E501
        :rtype: list[MultisigAccountInfoDTO]
        """
        return self._multisig_entries

    @multisig_entries.setter
    def multisig_entries(self, multisig_entries):
        """Sets the multisig_entries of this MultisigAccountGraphInfoDTO.


        :param multisig_entries: The multisig_entries of this MultisigAccountGraphInfoDTO.  # noqa: E501
        :type: list[MultisigAccountInfoDTO]
        """
        if multisig_entries is None:
            raise ValueError("Invalid value for `multisig_entries`, must not be `None`")  # noqa: E501

        self._multisig_entries = multisig_entries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MultisigAccountGraphInfoDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MultisigAccountGraphInfoDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
