# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.u_int64_dto import UInt64DTO  # noqa: F401,E501


class NamespaceNameDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parent_id': 'UInt64DTO',
        'namespace_id': 'UInt64DTO',
        'name': 'str'
    }

    attribute_map = {
        'parent_id': 'parentId',
        'namespace_id': 'namespaceId',
        'name': 'name'
    }

    def __init__(self, parent_id=None, namespace_id=None, name=None):  # noqa: E501
        """NamespaceNameDTO - a model defined in Swagger"""  # noqa: E501

        self._parent_id = None
        self._namespace_id = None
        self._name = None
        self.discriminator = None

        if parent_id is not None:
            self.parent_id = parent_id
        self.namespace_id = namespace_id
        self.name = name

    @property
    def parent_id(self):
        """Gets the parent_id of this NamespaceNameDTO.  # noqa: E501


        :return: The parent_id of this NamespaceNameDTO.  # noqa: E501
        :rtype: UInt64DTO
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this NamespaceNameDTO.


        :param parent_id: The parent_id of this NamespaceNameDTO.  # noqa: E501
        :type: UInt64DTO
        """

        self._parent_id = parent_id

    @property
    def namespace_id(self):
        """Gets the namespace_id of this NamespaceNameDTO.  # noqa: E501


        :return: The namespace_id of this NamespaceNameDTO.  # noqa: E501
        :rtype: UInt64DTO
        """
        return self._namespace_id

    @namespace_id.setter
    def namespace_id(self, namespace_id):
        """Sets the namespace_id of this NamespaceNameDTO.


        :param namespace_id: The namespace_id of this NamespaceNameDTO.  # noqa: E501
        :type: UInt64DTO
        """
        if namespace_id is None:
            raise ValueError("Invalid value for `namespace_id`, must not be `None`")  # noqa: E501

        self._namespace_id = namespace_id

    @property
    def name(self):
        """Gets the name of this NamespaceNameDTO.  # noqa: E501


        :return: The name of this NamespaceNameDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NamespaceNameDTO.


        :param name: The name of this NamespaceNameDTO.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NamespaceNameDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamespaceNameDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
