# coding: utf-8

"""
    Catapult REST API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.communication_timestamps import CommunicationTimestamps  # noqa: F401,E501


class NodeTimeDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'communication_timestamps': 'CommunicationTimestamps'
    }

    attribute_map = {
        'communication_timestamps': 'communicationTimestamps'
    }

    def __init__(self, communication_timestamps=None):  # noqa: E501
        """NodeTimeDTO - a model defined in Swagger"""  # noqa: E501

        self._communication_timestamps = None
        self.discriminator = None

        self.communication_timestamps = communication_timestamps

    @property
    def communication_timestamps(self):
        """Gets the communication_timestamps of this NodeTimeDTO.  # noqa: E501


        :return: The communication_timestamps of this NodeTimeDTO.  # noqa: E501
        :rtype: CommunicationTimestamps
        """
        return self._communication_timestamps

    @communication_timestamps.setter
    def communication_timestamps(self, communication_timestamps):
        """Sets the communication_timestamps of this NodeTimeDTO.


        :param communication_timestamps: The communication_timestamps of this NodeTimeDTO.  # noqa: E501
        :type: CommunicationTimestamps
        """
        if communication_timestamps is None:
            raise ValueError("Invalid value for `communication_timestamps`, must not be `None`")  # noqa: E501

        self._communication_timestamps = communication_timestamps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodeTimeDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeTimeDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
